config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :ideas do 
    resources :reviews, only: [:create, :destroy]
  end
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    alias_action(:create, :read, :update, :destroy, to: :crud)


    can(:crud, Idea) do |idea|
      user == idea.user

    end
    can(:crud, Review) do |review|
      user == review.user
    end



  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord
    has_many :reviews, dependent: :destroy

    belongs_to :user, optional: true


    before_save :capitalize_title

    validates :title, presence: true

    validates :description, presence: true



    
    def capitalize_title
        self.title.capitalize!
    end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :idea
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :ideas, dependent: :nullify
    has_many :reviews, dependent: :nullify
    def full_name
        "#{first_name} #{last_name}"
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def authenticate_user!
        redirect_to new_session_path, notice: "Please Sign in" unless user_signed_in?
    end




    def user_signed_in?
        current_user.present?
    end
    helper_method :user_signed_in?




    def current_user
    @current_user ||=User.find_by_id session[:user_id]
    end
    helper_method :current_user
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :authorize_user!, only: [:edit, :update, :destroy]

    before_action :find_idea, only: [:show, :edit, :update, :destroy]
    def index
        @idea = Idea.all
    end
    def new
        @idea = Idea.new
    end

    def create
        @idea = Idea.new params.require(:idea).permit(:title, :description)
        @idea.user = current_user
        if @idea.save
            flash[:notice] = "Idea created successfully"
            redirect_to ideas_path
        else render :new
        end
    end

    def show
        @idea = Idea.find params[:id]
        @review = Review.new
        @reviews = @idea.reviews


    end

    def edit
        @idea = Idea.find params[:id]

    end

    def update
        if @idea.update params.require(:idea).permit(:title, :description)
            redirect_to idea_path(@idea)
            else render :edit
        end

    end


    def destroy
        @idea.destroy

        redirect_to ideas_path

    end
    private
    def find_idea
        @idea = Idea.find params[:id]
    end
    def authorize_user!
        redirect_to ideas_path, alert:"Access Denied" unless can?(:crud, Idea)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    def create
    byebug
        @idea = Idea.find params[:idea_id]
        @review = Review.new params.require(:review).permit(:body)
        @review.user = current_user
        @review.idea = @idea
        if @review.save
            redirect_to idea_path(@idea)
        else
            redirect_to idea_path(@idea)
        end 
    end
    def destroy
        
        @review = Review.find params[:id]
        if can?(:crud, @review)
        @review.destroy
        redirect_to idea_path(@review.idea)
        else
            flash[:alert] = "not aurtorize "
        end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new


    end
    def create
    
        @user = User.find_by_email params[:email]
        if @user && @user.authenticate(params[:password]) 
            session[:user_id] = @user.id
            redirect_to ideas_path, notice: "Logged in"
        else 
            flash[:alert] = "Password or email not matching "
            render :new
        end
    end



    def destroy
        session[:user_id] = nil
        redirect_to ideas_path, notice: "Logged out!"
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end
    def create
        @user = User.new user_params
        if @user.save
            session[:user_id] = @user.id
            redirect_to ideas_path, notice: "Logged in"
        else render :new
        end

    end
    private
    def user_params
        params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ideas/create.html.erb
<h1><%= link_to "Home", idea %> </h1>

app/views/ideas/edit.html.erb
<% if @idea.errors.any? %>
<ul>
  <% @idea.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= form_for @idea do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <%= f.submit %>
<% end %>

app/views/ideas/index.html.erb
<div class="form-group">

<% @idea.each do |i| %>
    <div class="form-control">
      <%= link_to i.title, idea_path(i)%>
      </div>
      <hr>
      <div class="form-control">
      <%= i.description %>
      </div>
   
  <% end %>
  </div>
 
  

app/views/ideas/new.html.erb
<div>
<% if @idea.errors.any? %>
  <ul>
    <% @idea.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @idea do |f| %>
    <div>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div>
      <%= f.label :description %>
      <%= f.text_field :description %>
    </div>
    <%= f.submit %>
  <% end %>
  <d/iv>

app/views/ideas/show.html.erb
<div>
<h1> <%= @idea.title %></h1>
</div>
<hr>
<div>
<p> <%= @idea.description %></p>
By: <%= @idea.user&.full_name %>
</div>
<div>
<% if can?(:crud, @idea) %>
<%= link_to "Edit", edit_idea_path(@idea) %>
</div>
<div>

<%= link_to "Delete", idea_path(@idea), method: :delete %>
</div>
<% end %>
<h2>Reviews</h2>
<%= form_with(model: [@idea, @review], local: true) do |f| %>
    <%= f.text_area(
        :body,
        cols: 50,
        rows: 5
      )%>
      <%= f.submit "Review" %>
    <% end %>
    <ul>
    <% @reviews.each do |r| %>
        <li>
        <%= r.body %>
        <%= link_to(
            "Delete",
        idea_review_path(@idea, r),
          method: :delete )%>

    
        </li>
        <% end %>
        </ul>
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ideas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
  <%= flash[:notice] || flash[:alert] %>
  <%= link_to "New Idea?", new_idea_path(@idea) %>

  |

  <%= link_to "All ideas", ideas_path(@idea) %>

  |
  
  <%if user_signed_in? %>
  Hello <%= current_user.full_name %>,
  <%= link_to 'Log out', session_path, method: :delete %>
  <% else %>
  |
  <%= link_to 'Sign UP', new_user_path %>
  |
  <%= link_to "Login", new_session_path%> 
  <% end %>
  <hr>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @user do |f| %>
  <div>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <%= f.submit %>
<% end %>